export const ADMIN_LOGIN_LODING='ADMIN_LOGIN_LODING';
export const ADMIN_LOGIN_SUCCESS='ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILER='ADMIN_LOGIN_FAILER';
export const GET_ASTUDENT_REQUEST='GET_ASTUDENT_REQUEST';
export const GET_ASTUDENT_SUCCESS='GET_ASTUDENT_SUCCESS';
export const GET_ASTUDENT_FAILER='GET_ASTUDENT_FAILER';
export const GET_FACULTY_LIST="GET_FACULTY_LIST";
export const ADD_FACULTY="ADD_FACULTY";
export const DELETE_FACULTY="DELETE_FACULTY";
export const GET_DEPT_REQUEST='GET_DEPT_REQUEST';
export const GET_DEPT_SUCCESS='GET_DEPT_SUCCESS';
export const GET_DEPT_FAILER='GET_DEPT_FAILER';
export const RESGISTER_FACULTY_REQ='RESGISTER_FACULTY_REQ';
export const RESGISTER_FACULTY_SUCCESS='RESGISTER_FACULTY_SUCCESS';
export const RESGISTER_FACULTY_FAILER='RESGISTER_FACULTY_FAILER';
export const GET_SYNOPSIS_REQUEST='GET_SYNOPSIS_REQUEST';
export const GET_SYNOPSIS_SUCCESS='GET_SYNOPSIS_SUCCESS';
export const GET_SYNOPSIS_FAILER='GET_SYNOPSIS_FAILER';
export const GET_FACULTY_REQUEST='GET_FACULTY_REQUEST';
export const GET_FACULTY_SUCCESS='GET_FACULTY_SUCCESS';
export const GET_FACULTY_FAILER='GET_FACULTY_FAILER';
export const GET_SYNOPSISTOPRESENT_REQUEST='GET_SYNOPSISTOPRESENT_REQUEST';
export const GET_SYNOPSISTOPRESENT_SUCCESS='GET_SYNOPSISTOPRESENT_SUCCESS';
export const GET_SYNOPSISTOPRESENT_FAILER='GET_SYNOPSISTOPRESENT_FAILER';


